# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "attachments", :force => true do |t|
    t.column "content_type", :string, :limit => 100
    t.column "filename", :string
    t.column "size", :integer
    t.column "db_file_id", :integer
    t.column "path", :string
    t.column "parent_id", :integer
    t.column "thumbnail", :string
    t.column "width", :integer
    t.column "height", :integer
    t.column "image_format", :string
    t.column "aspect_ratio", :float
    t.column "depth", :integer
    t.column "colors", :integer
    t.column "colorspace", :string
    t.column "resolution", :string
    t.column "description", :text
    t.column "user_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "type", :string
  end

  create_table "collections", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "public", :boolean, :default => true
    t.column "user_id", :integer
    t.column "type", :string
    t.column "state_id", :integer
    t.column "parent_id", :integer
    t.column "counter_cache", :boolean, :default => true
  end

  create_table "db_files", :force => true do |t|
    t.column "data", :binary
  end

  create_table "linkings", :force => true do |t|
    t.column "user_id", :integer
    t.column "category_id", :integer
    t.column "group_id", :integer
    t.column "linkable_id", :integer
    t.column "linkable_type", :string
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "memberships", :force => true do |t|
    t.column "user_id", :integer
    t.column "collection_id", :integer
    t.column "collection_type", :string
    t.column "state_id", :integer, :default => 0
    t.column "created_at", :datetime
  end

  create_table "people", :force => true do |t|
    t.column "user_id", :integer
    t.column "first_name", :string, :limit => 200, :default => ""
    t.column "last_name", :string, :limit => 200, :default => ""
    t.column "gender", :integer, :default => 0, :null => false
    t.column "date_of_birth", :date
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
  end

  create_table "profiles", :force => true do |t|
    t.column "user_id", :integer
    t.column "created_on", :datetime
    t.column "updated_on", :datetime
    t.column "bio", :text
    t.column "address_line1", :string, :default => ""
    t.column "address_line2", :string, :default => ""
    t.column "city", :string, :default => ""
    t.column "state", :string, :default => ""
    t.column "country", :string, :default => ""
    t.column "postal_code", :string, :default => ""
    t.column "telephone", :string, :default => ""
    t.column "fax", :string, :default => ""
  end

  create_table "users", :force => true do |t|
    t.column "login", :string, :limit => 40
    t.column "email", :string, :limit => 100
    t.column "crypted_password", :string, :limit => 40
    t.column "salt", :string, :limit => 40
    t.column "activation_code", :string, :limit => 40
    t.column "activated_at", :datetime
    t.column "state", :integer, :default => 0
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "role", :integer, :default => 0
  end

end
